#!/usr/bin/env python3
"""Generate Nebula's settings catalog from V+'s preferences.xml.

Every V+ preference becomes a typed entry with the same SharedPreferences key, so the new
Settings screen edits exactly what the streaming engine reads. Re-run after changing
app/src/main/res/xml/preferences.xml:  python3 nebula/tools/gen_legacy_settings.py
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RES = ROOT / "app/src/main/res"
OUT = ROOT / "nebula/src/main/java/io/github/f_e_n_y_x/nebula/settings/LegacySettingsCatalog.kt"
A = "{http://schemas.android.com/apk/res/android}"
SB = "{http://schemas.moonlight-stream.com/apk/res/seekbar}"

strings = {}
for s in ET.parse(RES / "values/strings.xml").getroot().iter("string"):
    strings[s.get("name")] = "".join(s.itertext())
arrays = {}
for f in RES.glob("values/*.xml"):
    for a in ET.parse(f).getroot():
        if a.tag in ("string-array", "array", "integer-array"):
            arrays[a.get("name")] = ["".join(i.itertext()) for i in a.iter("item")]


def text(v):
    if v is None:
        return None
    if v.startswith("@string/"):
        v = strings.get(v[8:], v[8:])
    v = v.replace("\\'", "'").replace('\\"', '"').replace("\\n", "\n").strip()
    v = re.sub(r"<[^>]+>", "", v)
    return v.strip('"')


def arr(v):
    if not v:
        return []
    return [text(x) for x in arrays.get(v.split("/")[-1], [])]


def num(v, d=0):
    try:
        return int(v)
    except (TypeError, ValueError):
        return d


def kstr(s):
    if s is None:
        return "null"
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("\n", "\\n") + '"'


# Where each V+ category lands in Nebula's grouped settings.
GROUP = {
    "category_basic_settings": "stream",
    "category_advanced_features": "stream",
    "category_host_settings": "host",
    "category_framegen_settings": "framegen",
    "category_screen_position": "display",
    "category_display_behavior": "display",
    "category_ui_settings": "interface",
    "category_audio_settings": "audio",
    "category_microphone_settings": "audio",
    "category_gamepad_settings": "gamepads",
    "category_input_settings": "input",
    "category_onscreen_controls": "osc",
    "category_crown_features": "advanced",
    "category_backup_restore": "advanced",
    "category_help": "about",
}
# Items that are app-UI helpers of the old app (not stream behaviour) and have a native
# replacement in Nebula, or no meaning outside V+'s own screens.
SKIP = {
    "checkbox_small_icon_mode", "pref_reset_background_image", "pref_local_background_image",
    "list_languages", "pref_sponsor",
}

root = ET.parse(RES / "xml/preferences.xml").getroot()
entries = []
for cat in root:
    ckey = cat.get(A + "key")
    ctitle = text(cat.get(A + "title"))
    group = GROUP.get(ckey, "advanced")
    for p in cat:
        key = p.get(A + "key")
        if not key or key in SKIP:
            continue
        tag = p.tag.split(".")[-1]
        title = text(p.get(A + "title")) or key
        summary = text(p.get(A + "summary"))
        if summary and "%s" in summary:
            summary = None
        default = p.get(A + "defaultValue")
        dep = p.get(A + "dependency")
        if tag in ("CheckBoxPreference", "SwitchPreferenceCompat", "SmallIconCheckboxPreference"):
            kind = f"SettingKind.Toggle(default = {'true' if default == 'true' else 'false'})"
        elif tag in ("ListPreference", "IconListPreference"):
            names, values = arr(p.get(A + "entries")), arr(p.get(A + "entryValues"))
            opts = ", ".join(f"Choice({kstr(v)}, {kstr(n)})" for n, v in zip(names, values))
            kind = f"SettingKind.Pick(default = {kstr(default)}, choices = listOf({opts}))"
        elif tag == "SeekBarPreference":
            mn, mx = num(p.get(SB + "min")), num(p.get(A + "max"), 100)
            step = num(p.get(SB + "step"), 1) or 1
            div = num(p.get(SB + "divisor"), 1) or 1
            unit = text(p.get(A + "text")) or ""
            kind = f"SettingKind.Slider(default = {num(default, mn)}, min = {mn}, max = {mx}, step = {step}, divisor = {div}, unit = {kstr(unit)})"
        elif tag == "EditTextPreference":
            kind = f"SettingKind.Text(default = {kstr(text(default) or '')})"
        else:
            kind = f"SettingKind.Action(kind = {kstr(tag)})"
        entries.append(
            f"    SettingSpec(key = {kstr(key)}, group = {kstr(group)}, section = {kstr(ctitle)}, title = {kstr(title)}, "
            f"summary = {kstr(summary)}, dependsOn = {kstr(dep)}, kind = {kind}),"
        )

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    "// Generated by nebula/tools/gen_legacy_settings.py from app/src/main/res/xml/preferences.xml. Don't edit.\n"
    "package io.github.f_e_n_y_x.nebula.settings\n\n"
    "/** Every V+ preference, keyed exactly as the streaming engine reads it. */\n"
    "val legacySettings: List<SettingSpec> = listOf(\n" + "\n".join(entries) + "\n)\n"
)
print(f"{len(entries)} settings -> {OUT.relative_to(ROOT)}", file=sys.stderr)
